version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.11.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Отключите security, если не нужна
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk_net

  logstash:
    image: logstash:8.11.4
    ports:
      - "5044:5044"  # Для Filebeat
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk_net

  kibana:
    image: kibana:8.11.4
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk_net

volumes:
  es_data:
    driver: local

networks:
  elk_net:
    driver: bridge